<a href="https://colab.research.google.com/github/audrey-siqueira/Data-Science-Projects/blob/master/Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Churn Rate Prediction using Artificial Neural Network**
---
<p align="justify">
Churn rate, when applied to a customer base, refers to the proportion of contractual customers or subscribers who leave a supplier during a given time period. It is a possible indicator of customer dissatisfaction.

<p align=center>
<img src="https://drive.google.com/uc?id=1av3zO8GnEdNtaRqoP-CQzlbfOmgLPeh0" width="60%"></p>

<p align="justify">
A bank has a database with all its customers and their respective parameters such as: Credit Score, Nationality, Gender, Age, Balance, Estimated salary and etc, all of these parameters return the dependent variable, if the customer left (1) or not (0) the bank. The bank's shareholders want to do a study to predict the possibility of a customer leaves the bank. The Data Science department of this bank, which has the database mentioned above, can verify which customers have left the bank or not in the last few months and based on this history proposed a prediction model for next customers based on Deep Learning.

<p align=center>
<img src="https://drive.google.com/uc?id=1r6YkLmONo1OcStEkztuNjD4TeIMfkikY" width="40%"></p>


The strategy in this case is to use the **Artificial Neural Network** to forecast the Churn Rate of the Bank. 


**Code description is explained below:**

## **Part 1 - Data Preprocessing**

### **Importing the libraries**


The 3 libraries needed for the project are imported.
- Pandas for data manipulation and analysis
- Numpy for mathematical operations
- Tensorflow for Deep Learning

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
tf.__version__

'2.3.0'

### **Importing the data set**


The .csv file containing  database is imported.

The values of the database header and how they are distributed can be viewed in the image below:

In [ ]:
dataset = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Deep Learning/Artificial Neural Network/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
Y = dataset.iloc[:, -1].values
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

### **Encoding Categorical Data**

The **sklearn.compose** and **sklearn.preprocessing** libraries were used to transform categorical features in numeric values.

In [ ]:
#Encoding Gender
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

#Encoding Geography
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

print(X)


[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### **Splitting the dataset into the Training set and Test set**

The ***sklearn.model_selection*** library was used to divide the database between Training set and Test set. 

X and Y axes values were divided between Training set and Test set, resulting in 4 final vectors:
**X_train**, **X_test** and **Y_train**, **Y_test**

The database was divided in 80% of the total values for Training and 20% of the total values for Testing.

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

### **Feature Scaling**


Feature scaling is a method used to normalize the range of independent variables or features of data. In data processing, it is also known as data normalization and is generally performed during the data preprocessing step.

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

## **Part 2 - Creating the ANN**

### **Initializing the ANN**

In [ ]:
ann = tf.keras.models.Sequential()

### **Adding the input layer and the first hidden layer**

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### **Adding the second hidden layer**

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### **Adding the output layer**

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## **Part 3 - Training the ANN**

### **Compiling the ANN**

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### **Training the ANN on the Training set**

In [ ]:
ann.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 900us/step - loss: 0.6060 - accuracy: 0.6891
Epoch 2/100
250/250 [==============================] - 0s 899us/step - loss: 0.4685 - accuracy: 0.7961
Epoch 3/100
250/250 [==============================] - 0s 991us/step - loss: 0.4380 - accuracy: 0.8077
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4244 - accuracy: 0.8155
Epoch 5/100
250/250 [==============================] - 0s 906us/step - loss: 0.4179 - accuracy: 0.8183
Epoch 6/100
250/250 [==============================] - 0s 958us/step - loss: 0.4130 - accuracy: 0.8199
Epoch 7/100
250/250 [==============================] - 0s 936us/step - loss: 0.4090 - accuracy: 0.8216
Epoch 8/100
250/250 [==============================] - 0s 930us/step - loss: 0.4058 - accuracy: 0.8219
Epoch 9/100
250/250 [==============================] - 0s 953us/step - loss: 0.4023 - accuracy: 0.8236
Epoch 10/100
250/250 [==============================] - 0s 954us/step - los

## **Part 4 - Making the predictions and evaluating the model**

### **Predicting the Test set results**

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### **Making the Confusion Matrix**

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)
accuracy_score(Y_test, y_pred)

[[1511   84]
 [ 202  203]]


0.857

### **Predicting the result of a single observation**

In [ ]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]
